name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy.yml'
      - 'main.py'
      - 'game_of_life/**/*.py'
      - 'pyproject.toml'
      - 'poetry.lock'


permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "poetry"
          cache-dependency-path: poetry.lock

      - name: Install dependencies
        run: |
          poetry install
          sudo apt install libsdl2-2.0-0

      - name: Build application, prepare to deploy
        run: |
          make build.html
          rm -rf deploy
          mkdir deploy
          mv build.html deploy/index.html
          touch deploy/.nojekyll
          # mv build.pyxapp deploy/build.pyxapp

      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          git-config-name: github-actions[bot]
          git-config-email: 41898282+github-actions[bot]@users.noreply.github.com
          folder: deploy
          single-commit: true
