name: Tests
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/pytest.yml'
      - '**/*.py'
      - 'pyproject.toml'
      - 'poetry.lock'

  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/pytest.yml'
      - '**/*.py'
      - 'pyproject.toml'
      - 'poetry.lock'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "poetry"
          cache-dependency-path: poetry.lock

      - name: Install dependencies
        run: |
          poetry install
          # sudo apt install libsdl2-2.0-0

      - name: Build application, prepare to deploy
        run: |
          poetry run pytest
